version: "3.9"
services:
  trainer:
    build: ./
    image: midi-gen:cuda
    working_dir: /app
    volumes:
    - ./:/app
    gpus: all
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: bash -lc "python3 -m src.train --config config/config.yaml"


  generator:
    image: midi-gen:cuda
    working_dir: /app
    volumes:
    - ./:/app
    gpus: all
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: bash -lc "python3 -m src.generate --ckpt artifacts/models/best.pt --length 1500 --temperature 1.0 --out artifacts/samples/sample.mid"