seed: 42
midi_dir: data/midi
min_tokens: 256
seq_len: 512
batch_size: 16
num_workers: 2
vocab_size: 384
d_model: 512
nhead: 8
num_layers: 6
dim_feedforward: 2048
dropout: 0.1
lr: 3e-4
betas: [0.9, 0.95]
weight_decay: 0.01
max_steps: 2000
warmup_steps: 100
grad_clip: 1.0
val_interval: 200
ckpt_dir: artifacts/models
best_ckpt: artifacts/models/best.pt
temperature: 1.0
max_length: 1500